site_name: 'KYC-Component'
repo_url: https://github.com/surferslookout/bigbank-accelerator-kyc
repo_name: Github
edit_uri: blob/main/docs/
docs_dir: docs
nav:
  - Home: index.md
plugins:
  - techdocs-core

